export const ASSET_KEYS = {
  player: 'fighter-player',
  playerBanks: [
    'fighter-player-bank-hard-left',
    'fighter-player-bank-left',
    'fighter-player',
    'fighter-player-bank-right',
    'fighter-player-bank-hard-right',
  ],
  drone: 'fighter-drone',
  scout: 'enemy-scout',
  interceptor: 'enemy-interceptor',
  bomber: 'enemy-bomber',
  elite: 'enemy-elite',
  charger: 'enemy-charger',
  sniper: 'enemy-sniper',
  mineLayer: 'enemy-mine-layer',
  shieldCarrier: 'enemy-shield-carrier',
  warden: 'enemy-warden',
  boss: 'enemy-dreadnought',
  mine: 'hazard-mine',
  playerBullet: 'bullet-player',
  missile: 'bullet-missile',
  laser: 'bullet-laser',
  enemyBullet: 'bullet-enemy',
  enemyBulletHeavy: 'bullet-enemy-heavy',
  spark: 'fx-spark',
  cloud: 'fx-cloud',
  haze: 'fx-horizon-haze',
  foreground: 'fx-foreground-wisps',
  ocean: 'environment-ocean',
  coastal: 'environment-coastal-detail',
  minefield: 'environment-minefield-detail',
  fortress: 'environment-fortress-detail',
  dreadnought: 'environment-dreadnought-detail',
  pickupPrefix: 'pickup-',
} as const;
