export const ASSET_KEYS = {
  player: 'fighter-player',
  playerBanks: [
    'fighter-player-bank-hard-left',
    'fighter-player-bank-left',
    'fighter-player',
    'fighter-player-bank-right',
    'fighter-player-bank-hard-right',
  ],
  drone: 'fighter-drone',
  droneOverdrive: 'fighter-drone-overdrive',
  droneMk2: 'fighter-drone-mk2',
  droneMk2Overdrive: 'fighter-drone-mk2-overdrive',
  scout: 'enemy-scout',
  interceptor: 'enemy-interceptor',
  bomber: 'enemy-bomber',
  elite: 'enemy-elite',
  charger: 'enemy-charger',
  sniper: 'enemy-sniper',
  mineLayer: 'enemy-mine-layer',
  shieldCarrier: 'enemy-shield-carrier',
  bulwark: 'enemy-bulwark',
  phantom: 'enemy-phantom',
  artillery: 'enemy-artillery-skimmer',
  reclaimer: 'enemy-reclaimer-drone',
  razorwing: 'enemy-razorwing-ace',
  gatekeeper: 'enemy-gatekeeper-frigate',
  pursuer: 'enemy-crown-pursuer',
  carrierBoss: 'enemy-bastion-carrier',
  warden: 'enemy-warden',
  boss: 'enemy-dreadnought',
  mine: 'hazard-mine',
  playerBullet: 'bullet-player',
  playerBulletOverdrive: 'bullet-player-overdrive',
  wingBullet: 'bullet-wing',
  wingBulletOverdrive: 'bullet-wing-overdrive',
  missile: 'bullet-missile',
  missileOverdrive: 'bullet-missile-overdrive',
  laser: 'bullet-laser',
  laserOverdrive: 'bullet-laser-overdrive',
  enemyBullet: 'bullet-enemy',
  enemyBulletHeavy: 'bullet-enemy-heavy',
  spark: 'fx-spark',
  cloud: 'fx-cloud',
  haze: 'fx-horizon-haze',
  foreground: 'fx-foreground-wisps',
  ocean: 'environment-ocean',
  coastal: 'environment-coastal-detail',
  minefield: 'environment-minefield-detail',
  fortress: 'environment-fortress-detail',
  stormbreak: 'environment-stormbreak-detail',
  graveyard: 'environment-graveyard-detail',
  carrierSiege: 'environment-carrier-siege-detail',
  dreadnought: 'environment-dreadnought-detail',
  pickupPrefix: 'pickup-',
} as const;
